[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.7"
ticket_fields = { path = "../../../helpers/ticket_fields" }
serde = { version = "1.0.204", features = ["derive"] }
